version: '3'
services:
  consul_server1:
    command:
    - agent
    - -dev
    - -server
    container_name: consul_server1
    image: consul:1.3.1
    environment:
    - 'CONSUL_LOCAL_CONFIG={"session_ttl_min": "1s"}'
    - CONSUL_BIND_INTERFACE=eth0
  consul_server2:
    command:
    - agent
    - -dev
    - -server
    - -join=consul_server1
    container_name: consul_server2
    image: consul:1.3.1
    environment:
    - 'CONSUL_LOCAL_CONFIG={"session_ttl_min": "1s"}'
    - CONSUL_BIND_INTERFACE=eth0
    depends_on:
    - consul_server1
  consul_agent1:
    command:
    - agent
    - -dev
    - -join=consul_server1
    container_name: consul_agent1
    image: consul:1.3.1
    environment:
    - 'CONSUL_LOCAL_CONFIG={"session_ttl_min": "1s"}'
    - CONSUL_BIND_INTERFACE=eth0
    - CONSUL_CLIENT_INTERFACE=eth0
    depends_on:
    - consul_server1
  consul_agent2:
    command:
    - agent
    - -dev
    - -join=consul_server2
    container_name: consul_agent2
    image: consul:1.3.1
    environment:
    - 'CONSUL_LOCAL_CONFIG={"session_ttl_min": "1s"}'
    - CONSUL_BIND_INTERFACE=eth0
    - CONSUL_CLIENT_INTERFACE=eth0
    depends_on:
    - consul_server2
