version: '3'
services:
  consul_server1:
    command: "agent -server -node=consulserver1 -ui -client=0.0.0.0 -bootstrap-expect=2 -retry-join=consul_server2"
    container_name: consul_server1
    image: consul:1.3.1
    environment:
    - 'CONSUL_LOCAL_CONFIG={"session_ttl_min": "1s"}'
  consul_server2:
    command: "agent -server -node=consulserver2 -ui -client=0.0.0.0 -bootstrap-expect=2 -retry-join=consul_server1"
    container_name: consul_server2
    image: consul:1.3.1
    environment:
    - 'CONSUL_LOCAL_CONFIG={"session_ttl_min": "1s"}'
