FROM scion_app_base:latest
COPY --from=scion_app_builder:latest /home/scion/go/src/github.com/scionproto/scion/bin/ipprovider /app/

ENTRYPOINT ["/sbin/su-exec", "/app/ipprovider", "-config", "/share/conf/ipprovider.toml"]
