FROM scion_app_base:latest
COPY --from=scion_app_builder:latest /home/scion/go/src/github.com/scionproto/scion/bin/ipscraper /app/

ENTRYPOINT ["/sbin/su-exec", "/app/ipscraper", "-config", "/share/conf/ipscraper.toml"]
