CREATE TABLE Segments (
    RowID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    SegID bytea UNIQUE NOT NULL,
    FullID bytea UNIQUE NOT NULL,
    LastUpdated timestamp with time zone NOT NULL,
    InfoTs timestamp with time zone NOT NULL,
    Segment bytea NOT NULL,
    MaxExpiry timestamp with time zone NOT NULL,
    StartIsdID integer NOT NULL,
    StartAsID bigint NOT NULL,
    EndIsdID integer NOT NULL,
    EndAsID bigint NOT NULL
);

CREATE TABLE IntfToSeg(
    IsdID integer NOT NULL,
    AsID bigint NOT NULL,
    IntfID integer NOT NULL,
    SegRowID integer NOT NULL,
    FOREIGN KEY (SegRowID) REFERENCES Segments(RowID) ON DELETE CASCADE
);

CREATE TABLE SegTypes(
    SegRowID INTEGER NOT NULL,
    Type INTEGER NOT NULL,
    PRIMARY KEY (SegRowID, Type),
    FOREIGN KEY (SegRowID) REFERENCES Segments(RowID) ON DELETE CASCADE
);

CREATE TABLE HpCfgIds(
    SegRowID integer NOT NULL,
    IsdID integer NOT NULL,
    AsID bigint NOT NULL,
    CfgID bigint NOT NULL,
    PRIMARY KEY (SegRowID, IsdID, AsID, CfgID),
    FOREIGN KEY (SegRowID) REFERENCES Segments(RowID) ON DELETE CASCADE
);

CREATE TABLE NextQuery(
    IsdID integer NOT NULL,
    AsID bigint NOT NULL,
    NextQuery timestamp with time zone NOT NULL,
    PRIMARY KEY (IsdID, AsID)
);

CREATE TABLE Revocations(
    RowID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    IsdID integer NOT NULL,
    AsID bigint NOT NULL,
    IfID integer NOT NULL,
    LinkType integer NOT NULL,
    RawTimeStamp bigint NOT NULL,
    RawTTL bigint NOT NULL,
    RawSignedRev bytea NOT NULL,
    UNIQUE (IsdID, AsID, IfID)
);
