#!/bin/bash

set -e

# Anapaya needs a docker login
echo "Login to docker hub with user $DOCKERHUB_USER"
echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

BASE_IMG=${BASE_IMG:-085c21fbcf8717a6a0fa4a8a1d290fa7608e4db921f0f5bc4653b939bc7aced3}

./tools/ci/prepare_image "$BASE_IMG"
./docker.sh build
