version: '3'
services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    image: postgres:10
    network_mode: bridge
    ports:
    - 5432:5432
    volumes:
    - '${BASE_DIR}/initsql:/docker-entrypoint-initdb.d:ro'
