#!/bin/bash

# Copyright Anapaya Systems 2019

# Tests the patroni pathdb backend implementation.

TEST_NAME="patroni_pathdb"
PROGRAM=$(basename "$0")
COMMAND="$1"

. acceptance/patroni/common.sh

test_setup() {
    set -e
    base_setup "acceptance/patroni_pathdb_acceptance/initsql/"
}

test_run() {
    CONSUL_ADDRESS="$(container_ip $CONSUL1):8500" go test ./go/lib/pathdb/patronipathdb -v -tags patronirunning
}

test_teardown() {
    base_teardown
}

do_command $PROGRAM $COMMAND $TEST_NAME ${@:2}
